import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useAuth } from '@/auth/AuthContext'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { Field, Input, Textarea } from '@/components/ui/Field'
import { EmptyState, ErrorState, Skeleton } from '@/components/ui/States'
import { api, ApiError } from '@/lib/apiClient'
import { formatDateTime, relativeTime } from '@/lib/format'

type Tab = 'forum' | 'announcements' | 'events'
type Post = { id: string; title: string; content: string; createdAt: string; author: { name: string }; replyCount: number; isLocked?: boolean; replies?: Reply[] }
type Reply = { id: string; content: string; author: { name: string }; createdAt: string }
type Announcement = { id: string; title: string; content: string; publishedAt: string }
type Event = { id: string; title: string; description: string; location: string; eventDate: string; attendeeCount: number }

// Turn on only after the backend team confirms unit scoping, moderation and RSVP checks.
const WRITES_ENABLED = import.meta.env.VITE_COMMUNITY_WRITES_ENABLED === 'true'
const errorText = (error: unknown) => error instanceof ApiError ? error.message : 'Could not save. Please check your connection and retry.'

export function LiveCommunityPage() {
  const { role } = useAuth()
  const client = useQueryClient()
  const [tab, setTab] = useState<Tab>('forum')
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [title, setTitle] = useState('')
  const [content, setContent] = useState('')
  const [reply, setReply] = useState('')
  const [eventDescription, setEventDescription] = useState('')
  const [eventLocation, setEventLocation] = useState('')
  const [eventDate, setEventDate] = useState('')
  const [rsvped, setRsvped] = useState<string[]>([])

  const posts = useQuery({ queryKey: ['community', 'posts'], queryFn: () => api.get<{ posts: Post[] }>('/community/posts'), enabled: tab === 'forum' })
  const detail = useQuery({ queryKey: ['community', 'post', selectedId], queryFn: () => api.get<{ post: Post }>(`/community/posts/${selectedId}`), enabled: tab === 'forum' && !!selectedId })
  const announcements = useQuery({ queryKey: ['community', 'announcements'], queryFn: () => api.get<{ announcements: Announcement[] }>('/community/announcements'), enabled: tab === 'announcements' })
  const events = useQuery({ queryKey: ['community', 'events'], queryFn: () => api.get<{ events: Event[] }>('/community/events'), enabled: tab === 'events' })

  const createPost = useMutation({ mutationFn: () => api.post('/community/posts', { title: title.trim(), content: content.trim() }), onSuccess: () => { setTitle(''); setContent(''); void client.invalidateQueries({ queryKey: ['community', 'posts'] }) } })
  const createReply = useMutation({ mutationFn: () => api.post('/community/replies', { postId: selectedId, content: reply.trim() }), onSuccess: () => { setReply(''); void client.invalidateQueries({ queryKey: ['community', 'post', selectedId] }); void client.invalidateQueries({ queryKey: ['community', 'posts'] }) } })
  const createAnnouncement = useMutation({ mutationFn: () => api.post('/community/announcements', { title: title.trim(), content: content.trim() }), onSuccess: () => { setTitle(''); setContent(''); void client.invalidateQueries({ queryKey: ['community', 'announcements'] }) } })
  const createEvent = useMutation({ mutationFn: () => api.post('/community/events', { title: title.trim(), description: eventDescription.trim(), location: eventLocation.trim(), eventDate: new Date(eventDate).toISOString(), type: 'meeting' }), onSuccess: () => { setTitle(''); setEventDescription(''); setEventLocation(''); setEventDate(''); void client.invalidateQueries({ queryKey: ['community', 'events'] }) } })
  const rsvp = useMutation({ mutationFn: (id: string) => api.post(`/community/events/${id}/rsvp`, {}), onSuccess: (_, id) => { setRsvped(current => [...current, id]); void client.invalidateQueries({ queryKey: ['community', 'events'] }) } })

  const canPublish = role === 'unit_admin' || role === 'super_admin'
  function submit(event: FormEvent, mutation: { mutate: () => void }) { event.preventDefault(); if (WRITES_ENABLED) mutation.mutate() }

  return <div className="mx-auto max-w-3xl space-y-4 p-4 sm:p-6">
    <header><h1 className="text-xl font-semibold text-ink">Community</h1><p className="mt-1 text-sm text-ink-muted">Discuss local preparedness and find unit announcements and events.</p></header>
    {!WRITES_ENABLED && <p role="status" className="rounded-lg border border-warn/40 bg-warn/10 p-3 text-sm text-ink">Community publishing and RSVP are being reviewed. You can read posts, announcements, and events here.</p>}
    <nav aria-label="Community sections" className="flex flex-wrap gap-2">{(['forum', 'announcements', 'events'] as const).map(item => <Button key={item} size="sm" variant={tab === item ? 'primary' : 'secondary'} aria-pressed={tab === item} onClick={() => { setTab(item); setSelectedId(null); setTitle(''); setContent('') }}>{item === 'forum' ? 'Discussions' : item[0].toUpperCase() + item.slice(1)}</Button>)}</nav>

    {tab === 'forum' && <section aria-label="Community discussions" className="space-y-4">
      {WRITES_ENABLED && <Card className="p-4"><form className="space-y-3" onSubmit={event => submit(event, createPost)}><h2 className="font-semibold text-ink">Start a discussion</h2><Field label="Title" required>{props => <Input {...props} maxLength={120} required value={title} onChange={e => setTitle(e.target.value)} />}</Field><Field label="Message" required>{props => <Textarea {...props} maxLength={2000} required value={content} onChange={e => setContent(e.target.value)} />}</Field><Button variant="primary" type="submit" disabled={!title.trim() || !content.trim()} loading={createPost.isPending}>Publish post</Button>{createPost.isError && <p role="alert" className="text-sm text-emergency">{errorText(createPost.error)}</p>}</form></Card>}
      {selectedId ? <><Button size="sm" onClick={() => setSelectedId(null)}>Back to discussions</Button>{detail.isLoading ? <Skeleton className="h-36 w-full" /> : detail.isError ? <Card><ErrorState title="Could not load discussion" description="Try again." onRetry={() => void detail.refetch()} /></Card> : detail.data && <Card className="space-y-3 p-4"><h2 className="font-semibold text-ink">{detail.data.post.title}</h2><p className="text-xs text-ink-faint">{detail.data.post.author?.name ?? 'Community member'} · {relativeTime(detail.data.post.createdAt)}</p><p className="whitespace-pre-wrap text-sm text-ink-muted">{detail.data.post.content}</p><h3 className="border-t border-border pt-3 text-sm font-semibold text-ink">Replies</h3>{detail.data.post.replies?.length ? <ul className="space-y-3">{detail.data.post.replies.map(item => <li key={item.id} className="rounded-lg bg-surface-hi p-3"><p className="whitespace-pre-wrap text-sm text-ink">{item.content}</p><p className="text-xs text-ink-faint">{item.author?.name ?? 'Community member'} · {relativeTime(item.createdAt)}</p></li>)}</ul> : <p className="text-sm text-ink-muted">No replies yet.</p>}{WRITES_ENABLED && !detail.data.post.isLocked && <form className="space-y-3" onSubmit={event => submit(event, createReply)}><Field label="Your reply" required>{props => <Textarea {...props} maxLength={1000} required value={reply} onChange={e => setReply(e.target.value)} />}</Field><Button type="submit" variant="primary" disabled={!reply.trim()} loading={createReply.isPending}>Reply</Button>{createReply.isError && <p role="alert" className="text-sm text-emergency">{errorText(createReply.error)}</p>}</form>}{detail.data.post.isLocked && <p className="text-sm text-ink-muted">This discussion is locked.</p>}</Card>}</> : posts.isLoading ? <Skeleton className="h-28 w-full" /> : posts.isError ? <Card><ErrorState title="Could not load discussions" description="Try again." onRetry={() => void posts.refetch()} /></Card> : posts.data?.posts.length ? <ul className="space-y-3">{posts.data.posts.map(post => <li key={post.id}><Card className="p-4"><button className="w-full text-left" onClick={() => setSelectedId(post.id)}><h2 className="font-semibold text-ink">{post.title}</h2><p className="text-xs text-ink-faint">{post.author?.name ?? 'Community member'} · {relativeTime(post.createdAt)} · {post.replyCount} replies</p><p className="mt-2 whitespace-pre-wrap text-sm text-ink-muted">{post.content}</p><span className="mt-2 inline-block text-sm text-signal">Read discussion</span></button></Card></li>)}</ul> : <Card><EmptyState title="No discussions yet" description="Check back later." /></Card>}
    </section>}

    {tab === 'announcements' && <section aria-label="Announcements" className="space-y-4">{WRITES_ENABLED && canPublish && <Card className="p-4"><form className="space-y-3" onSubmit={event => submit(event, createAnnouncement)}><h2 className="font-semibold text-ink">Publish announcement</h2><Field label="Title" required>{props => <Input {...props} required maxLength={120} value={title} onChange={e => setTitle(e.target.value)} />}</Field><Field label="Message" required>{props => <Textarea {...props} required maxLength={2000} value={content} onChange={e => setContent(e.target.value)} />}</Field><Button type="submit" variant="primary" disabled={!title.trim() || !content.trim()} loading={createAnnouncement.isPending}>Publish</Button>{createAnnouncement.isError && <p role="alert" className="text-sm text-emergency">{errorText(createAnnouncement.error)}</p>}</form></Card>}{announcements.isLoading ? <Skeleton className="h-24 w-full" /> : announcements.isError ? <Card><ErrorState title="Could not load announcements" description="Try again." onRetry={() => void announcements.refetch()} /></Card> : announcements.data?.announcements.length ? <ul className="space-y-3">{announcements.data.announcements.map(item => <li key={item.id}><Card className="p-4"><h2 className="font-semibold text-ink">{item.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm text-ink-muted">{item.content}</p><p className="text-xs text-ink-faint">{relativeTime(item.publishedAt)}</p></Card></li>)}</ul> : <Card><EmptyState title="No announcements" description="Nothing has been posted." /></Card>}</section>}

    {tab === 'events' && <section aria-label="Events" className="space-y-4">{WRITES_ENABLED && canPublish && <Card className="p-4"><form className="space-y-3" onSubmit={event => submit(event, createEvent)}><h2 className="font-semibold text-ink">Create event</h2><Field label="Title" required>{props => <Input {...props} required value={title} onChange={e => setTitle(e.target.value)} />}</Field><Field label="Description" required>{props => <Textarea {...props} required value={eventDescription} onChange={e => setEventDescription(e.target.value)} />}</Field><Field label="Location" required>{props => <Input {...props} required value={eventLocation} onChange={e => setEventLocation(e.target.value)} />}</Field><Field label="Start time" required>{props => <Input {...props} required type="datetime-local" value={eventDate} onChange={e => setEventDate(e.target.value)} />}</Field><Button type="submit" variant="primary" disabled={!title.trim() || !eventDescription.trim() || !eventLocation.trim() || !eventDate} loading={createEvent.isPending}>Create event</Button>{createEvent.isError && <p role="alert" className="text-sm text-emergency">{errorText(createEvent.error)}</p>}</form></Card>}{events.isLoading ? <Skeleton className="h-24 w-full" /> : events.isError ? <Card><ErrorState title="Could not load events" description="Try again." onRetry={() => void events.refetch()} /></Card> : events.data?.events.length ? <ul className="space-y-3">{events.data.events.map(item => <li key={item.id}><Card className="space-y-2 p-4"><h2 className="font-semibold text-ink">{item.title}</h2><p className="text-sm text-ink-muted">{item.description}</p><p className="text-xs text-ink-faint">{item.location} · {formatDateTime(item.eventDate)} · {item.attendeeCount} attending</p>{WRITES_ENABLED && <Button size="sm" disabled={rsvped.includes(item.id)} loading={rsvp.isPending && rsvp.variables === item.id} onClick={() => rsvp.mutate(item.id)}>{rsvped.includes(item.id) ? 'RSVP recorded' : 'RSVP'}</Button>}{rsvp.isError && rsvp.variables === item.id && <p role="alert" className="text-sm text-emergency">{errorText(rsvp.error)}</p>}</Card></li>)}</ul> : <Card><EmptyState title="No upcoming events" description="Check back later." /></Card>}</section>}
  </div>
}
