import { Link } from 'react-router-dom'
import { Card } from '@/components/ui/Card'

/** Plain-language product rules. Publication as binding legal terms requires owner review. */
export function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-3xl space-y-5 p-4 sm:p-6">
      <header><Link to="/" className="text-sm text-signal hover:underline">← Nativity Guard</Link><h1 className="mt-3 text-2xl font-semibold text-ink">Using Nativity Guard responsibly</h1><p className="mt-2 text-sm text-ink-muted">Guidance for citizens, officers, unit administrators, and platform administrators. Read the rules that apply to your role before using operational features.</p></header>
      <Card className="space-y-2 p-5"><h2 className="font-semibold text-ink">For everyone</h2><ul className="list-disc space-y-1 pl-5 text-sm text-ink-muted"><li>Give accurate information to the best of your knowledge. Do not submit knowingly false reports, impersonate someone, or harass others.</li><li>Share only information you are allowed to share. Avoid posting another person’s private details, images, or case evidence in community discussions.</li><li>Keep your sign-in details private and report suspicious account activity through the appropriate support channel.</li><li>Use SOS for genuine urgent situations. An app request may be delayed or unavailable; contact local emergency services directly when immediate help is needed.</li><li>AI suggestions and map activity are informational. They are not verified safety decisions or proof that an area is safe or dangerous.</li></ul></Card>
      <Card className="space-y-2 p-5"><h2 className="font-semibold text-ink">Citizens</h2><p className="text-sm text-ink-muted">Report incidents truthfully, provide updates relevant to your own report, and respect the privacy of victims, witnesses, and suspects. Do not use public comments to publish allegations or identifying evidence. Your report is reviewed by authorised personnel; submitting it does not guarantee an immediate response or a particular outcome.</p></Card>
      <Card className="space-y-2 p-5"><h2 className="font-semibold text-ink">Officers</h2><p className="text-sm text-ink-muted">Access cases only for assigned duties. Record actions and progress accurately, protect evidence, and follow your unit’s approval and escalation procedures. Do not export, share, or alter case records for personal reasons. Treat AI output as a suggestion requiring independent checking.</p></Card>
      <Card className="space-y-2 p-5"><h2 className="font-semibold text-ink">Unit administrators</h2><p className="text-sm text-ink-muted">Grant and review access only for legitimate unit work. Review case decisions, assignments, and public notices through the authorised workflow. Maintain an audit trail and protect the privacy of reporters and staff. Do not use administrator access to bypass case permissions.</p></Card>
      <Card className="space-y-2 p-5"><h2 className="font-semibold text-ink">Platform administrators</h2><p className="text-sm text-ink-muted">Use platform-wide access only for approved operational, security, and governance tasks. Keep role changes and sensitive actions accountable, investigate misuse fairly, and apply the same privacy and evidence safeguards across units.</p></Card>
      <Card className="space-y-2 p-5"><h2 className="font-semibold text-ink">Privacy and account controls</h2><p className="text-sm text-ink-muted">The app uses account details, reports, locations you submit, and operational records to provide its services. Access varies by role. You can edit supported profile details and manage signed-in devices in Settings. Data access, correction, or deletion requests need a verified support process; no self-service export or deletion is offered here yet.</p><p className="text-sm text-ink-muted">This page describes expected use. The service owner must publish a separate, reviewed privacy notice covering the actual data controller, contacts, purposes, retention, sharing, and rights process.</p></Card>
      <p className="text-xs text-ink-faint">Product guidance draft · 29 September 2026. The service owner must review and approve binding legal terms and publish a version and effective date before collecting acceptance.</p>
    </main>
  )
}
